### ISSUE TITLE
Fields are output into different order at random times

### ISSUE THREAD

**Issue by mcgaritydotme** [thingsapi/things-cli#19]
**To Reproduce**
1. Run the following CLI command: `things-cli --csv all > tasks.csv`
2. Open `tasks.csv` in any editor
3. Make note of the column labels and their order
4. Repeat the above steps

**Expected behavior**
Each time the export is done, the same columns are exported in the same order

**Additional context**
Not every time, but I run the export once per week, and the column headers will shift position:

Column order on 2024-02-07 export:
`title	uuid	type	status	area	area_title	notes	tags	start	start_date	deadline	stop_date	created	modified	index	today_index	project	project_title	heading	heading_title`

Column order on 2024-02-12 export (notice how the `project*` and `heading*` fields are swapped):
`title	uuid	type	status	area	area_title	notes	tags	start	start_date	deadline	stop_date	created	modified	index	today_index	heading	heading_title	project	project_title`

Column order on 2024-02-19 export (fields are now in a completely-different order): 
`title	uuid	type	status	notes	start	start_date	deadline	stop_date	created	modified	index	today_index	area	area_title	tags	project	project_title	heading	heading_title`

**Why is this important?**

I import Things 3 tasks into a custom spreadsheet in order to perform analytics, but it expects the input (tasks.csv) to be the same structure each time.  Reordering of columns breaks these analytics.

**Comment by AlexanderWillner** [comment]
Thanks, that's interesting. Not sure why this happens...

**Comment by mbhutton** [comment]
> Thanks, that's interesting. Not sure why this happens...

@AlexanderWillner My guess is because the list of headers is populated by iterating over tasks and their fields. So eg if task 1 has `notes` and/or `area`, and task 2 does not, then their order would affect when the fields are discovered. 

```
 def csv_header(self, tasks, fieldnames):
        """Convert tasks into CSV header."""
        for task in tasks:
            fieldnames.extend(field for field in task if field not in fieldnames)
            self.csv_header(task.get("items", []), fieldnames)
```

Fixable by:
```
           fieldnames = []
           self.csv_header(tasks, fieldnames)
           [...]
+++        fieldnames.sort()  # Because task content affects the order that fields are discovered above
```

Will test and raise a PR as above. 

Note that @mcgaritydotme's case, this wouldn't address the problem of columns either being present or absent based on task content. Eg doing an export when no `notes` fields are present at all, vs an export which contains some tasks with `notes` - the column would either be present or absent. Would be fixable, but would be a more complicated fix, and not sure if users would want unused columns in their CSV export anyway. Always including all columns (including unused) would require some way of enumerating all available fields including those not current used.
